version: '3.8'

networks:
  backend:
    driver: bridge

services:
  app:
    build:
      context: ./
    ports:
      - "8080:8080"
    depends_on:
      - db
    networks:
      - backend
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/timeclock?serverTimezone=Asia/Taipei&characterEncoding=utf-8
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: 82958654

  db:
    image: mysql:8.3
    environment:
      MYSQL_ROOT_PASSWORD: 82958654
      MYSQL_DATABASE: timeclock
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
      MYSQL_ALLOW_PUBLIC_KEY_RETRIEVAL: 'true'
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - backend

volumes:
  db_data: